version: "3"

services:
  bot:
    container_name: twitchbot_bot
    build: ./bot/
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./bot/configs:/workspace/bot/configs/
      - ./bot/irc_logs:/workspace/bot/irc_logs/
      - ./bot/jsons:/workspace/bot/jsons/
      - ./models.py:/workspace/bot/models.py
      # - ./bot:/workspace/bot/
    environment:
      client_id: ${TWITCH_CLIENT_ID} #Lower cased because a framework issue
      client_secret: ${TWITCH_CLIENT_SECRET}
      nick: ${TWITCH_NICK}
      oauth: ${TWITCH_OAUTH}
      PUBSUB_OAUTH: ${TWITCH_PUBSUB_OAUTH}
      ADAFRUIT_IO_USER: ${ADAFRUIT_IO_USER}
      ADAFRUIT_IO_KEY: ${ADAFRUIT_IO_KEY}
      WEB_HOSTNAME: ${WEB_HOSTNAME}
      TWITCH_CHANNEL: ${TWITCH_CHANNEL}

  webserver:
    container_name: twitchbot_webserver
    build: ./web/
    restart: unless-stopped
    expose:
      - 5000
    depends_on:
      - mysql

    volumes:
      - ./models.py:/workspace/web/models.py
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`${WEB_HOSTNAME}`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
      - "deck-chores.webhook-subscribe.command=sh -c /workspace/web/webhook_requests.py &> /proc/1/fd/1"
      - "deck-chores.webhook-subscribe.cron=* * * * * */6 0 0"

    environment:
      WEB_HOSTNAME: ${WEB_HOSTNAME}
      CLIENT_ID: ${TWITCH_CLIENT_ID}
      CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      PUBSUB_OAUTH: ${TWITCH_PUBSUB_OAUTH}
      TWITCH_CHANNEL: ${TWITCH_CHANNEL}
      ADAFRUIT_IO_USER: ${ADAFRUIT_IO_USER}
      ADAFRUIT_IO_KEY: ${ADAFRUIT_IO_KEY}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WEB_API_KEY: ${WEB_API_KEY}
      TWITCH_SIGNING_SECRET: ${TWITCH_SIGNING_SECRET}
      WEB_COOKIE_KEY: ${WEB_COOKIE_KEY}

    # Uncommenting these disables the requirement to re-build on updates, useful for dev.
    # volumes:
    #   - ./web:/workspace/web/

  mysql:
    container_name: twitchbot_mysql
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./mysql/db_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    cap_add:
      - SYS_NICE # CAP_SYS_NICE

  traefik:
    container_name: twitchbot_traefik
    image: traefik:v2.3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "./traefik/acme.json:/acme.json"
      - "./traefik/log:/var/log"
    environment:
      - "TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL"

  fail2ban:
    container_name: twitchbot_fail2ban
    image: crazymax/fail2ban:latest
    network_mode: "host"
    environment:
      F2B_DB_PURGE_AGE: "1d"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    volumes:
      - ./traefik/log:/var/log/traefik:ro
      - ./fail2ban/data:/data

  chores:
    container_name: twitchbot_chores
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
